### PR TITLE
fixed login with chrome browser

### PR DESCRIPTION
**Pull request by frnktrgr**
- fix 'environment-variable' login problem with chrome browser
- problem: using nextcloud behind apache2 mod_auth_mellon, chrome browser gets too many redirects
- description: nc_sameSiteCookiestrict is not sent by chrome, because of the origin POST request by idp and the 3xx redirects on nextcloud side

### CODE REVIEW

**Comment by linuxrrze** [comment]
Just re-confirmed with nextcloud 12.0.3 / user_saml 1.4.0 (also tried latest git of user_saml)

user_saml is running in "environment-variable" mode, with multiple IdPs.

IdP with same domain name as nextcloud server works, IdP with different domain gives "too many redirects" in chrome browser (version 61, same behavior in all previous versions of chrome)
Doing a manual reload results in successful login.
This effect was not observed with other browsers.

**Comment by linuxrrze** [comment]
Just wanted to re-confirm:
Bug is still there with nextcloud 12.0.4 (user_saml app version: 1.4.0 (unchanged)).
Patch (still) resolves issue.

Please review and merge.

**Comment by linuxrrze** [comment]
Now that nextcloud 13 is going to be released soon: any chance of merging this?

**Comment by yennor** [comment]
would be absolutely great if that could be merged. just stumpled over t he s ame issue (and lost way too much time over it)

**Comment by mclegrand** [comment]
Fixed the requesttoken loop for me too (fresh install of 15.0.2)

**Comment by linuxrrze** [comment]
Ok - the PR seems to fix the problem for lots of people (abd over a wide variety of versions)!

When can we expect this to get merged?

**Comment by anicoa** [comment]
Had the same problem with nginx and user_saml if user visiting site from idp after authentication directly on idp site.

Can we help with work or money to get this merged?  @LukasReschke

**Comment by staeglis** [comment]
The patch works also for me

**Comment by flu0** [comment]
Tested and confirmed fix working properly on NC 15.0.7 + user_saml 2.2.0. Also seems to fix #225/#169.

**Comment by linuxrrze** [comment]
I wonder how many more confirmations it will take, until someone is willing to merge this?
Maybe we're doing something wrong, so please let us know:

What's the usual way of getting things merged in nextcloud?

I think the fix is quite simple and according to peoples feedback required by quite some people.

Please don't get me wrong:
I do not want to be impolite, but as an open source and nextcloud enthusiast I cannot understand why existing fixes do not get applied ASAP. That's frustrating for people using the software and encountering this bug as well as for the people who spent their time researching and fixing it.

**Comment by kort3z** [comment]
Thank you very much @linuxrrze , this PR fixed all my issues with NC 15.0.7 and User_Saml 2.2.0 ! 

I don't know why this PR is under review since 2 years ! 

Please let someone merge that !

**Comment by brtptrs** [comment]
Referring to:
https://github.com/nextcloud/user_saml/issues/248
I've just tested this on NC18 with user_saml 2.5.0. 
The problem still exists and is solved by:
https://github.com/nextcloud/user_saml/pull/147/files

**Comment by blizzz** [comment]
@frnktrgr if you're still up to it, do you mind rebasing?

**Comment by rullzer** [comment]
Ah mmmm me pushing to upstream failed. let me create a new PR

**Pull request closed without merging**
