### PR TITLE
Add SPDX header

### PR DESCRIPTION
**Pull request by AndyScherzinger**
and GH action to check PRs

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
> Seems there is something wrong with the dependabot file.

@blizzz actually that issue is present even before this PR and the changes in the file have no effect on this. If you revert any change in the dependabot file you will still see the exact same error. See https://github.com/dependabot/dependabot-core/issues/8948 for others facing the same issue...

**Comment by blizzz** [comment]
Seems to be a layer 8 origin. https://github.com/nextcloud/user_saml/pull/751#issuecomment-1638721012

It did not turn red before though.

**Comment by blizzz** [comment]
> Add [7f33a3e](https://github.com/nextcloud/user_saml/commit/7f33a3e8f74df2d78af5c51827a9dc24f6b2f3a5) to show it breaks anyways @blizzz

dropped the commit again

**Review by blizzz — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Thanks @blizzz

All green now 💚

**Pull request merged**
