### PR TITLE
Add counting to the user backend

### PR DESCRIPTION
**Pull request by rullzer**
This will allow reporting to also list the number of SAML users on the
instance.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
CI is not fully happy but that seems unrelated. Lets have a look separately.

**Comment by blizzz** [comment]
tests bricked by server changes:

```
PHP Fatal error: Declaration of OCA\User_SAML\Tests\AppInfo\ApplicationTest::setUp() must be compatible with Test\TestCase::setUp(): void in /drone/server/apps/user_saml/tests/unit/AppInfo/ApplicationTest.php on line 31
```

**Comment by rullzer** [comment]
Ah right we need to fix those...

**Pull request merged**
