### PR TITLE
remove leading and trailing white space from settings

### PR DESCRIPTION
**Pull request by schiessle**
remove leading and trailing white space from settings to make it a little bit harder to break your SAML settings :wink:

### CODE REVIEW

**Comment by schiessle** [comment]
Any idea why the integration tests fail?

**Comment by blizzz** [comment]
Yes! The LDAP server is down or unreachable:

```
.. initialized=false, availableCount=0, activeCount=0] unable to connect to the ldap
org.ldaptive.provider.ConnectionException: javax.naming.CommunicationException: localhost:389 [Root exception is java.net.ConnectException: Connection refused (Connection refused)]
```

I guess, debbuging the CI image is key.

**Comment by schiessle** [comment]
@MorrisJobke that's coming from our general CI setup right, there is no special image for the user_saml tests? Do you have a idea what's broken here and what's the best way to debug it?

**Comment by MorrisJobke** [comment]
> @MorrisJobke that's coming from our general CI setup right, there is no special image for the user_saml tests? Do you have a idea what's broken here and what's the best way to debug it? Is there an easy way to execute the tests locally?

* install drone cli tool - https://0-8-0.docs.drone.io/cli-installation/
* `drone exec`

That executes all of them. Often I removed then the stuff I'm not interested in from the `.drone.yml`.

For the integration tests you could also execute the commands from here manually:

https://github.com/nextcloud/user_saml/blob/master/.drone.yml#L83-L94

**Comment by schiessle** [comment]
ok, let's get this in and look at the tests independent from this pr

**Pull request merged**
