### PR TITLE
Add original url for redirect when using SSO

### PR DESCRIPTION
**Pull request by jbpin**
When using environment variable setting the originalUrl params is not used for redirecting the request.
This request is to add originalUrl as a redirect value when using SSO with environment variables or to fallback to the root path.

### CODE REVIEW

**Comment by schiessle** [comment]
make sense to me, @rullzer what do you think?

**Comment by schiessle** [comment]
@jbpin can you please sign your commit, see https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work and rebase your branch to latest master so that we can re-run the tests? Thanks!

**Comment by jagland** [comment]
I'd like to see this issue resolved please, I raised a similar PR months ago in https://github.com/nextcloud/user_saml/pull/209 and it was ignored.

@jbpin looks like you are still failing tests from what I can see (details below).  Related to having commits without ```Signed-off-by: ```?
Maybe @schiessle can guide you on what is required to correct that?

https://drone.nextcloud.com/nextcloud/user_saml/685/13

```
Some commits were not signed off!
Missing signatures on:
- e167e7eef5abb43accfb26154998bb5434793f43
- 41f50e23b2a04952df2bcbafa018a6200b4dba1c
Build has failed
```

**Comment by schiessle** [comment]
yes, it is just the sign off which is missing, otherwise it looks good.

@jbpin just do a `git commit --amend -s` you should see your commit message with a signoff added at the end. Save the new commit message and do a force push on your branch.

I plan to do a new release on Friday and would be happy to add it. :smile:

**Comment by jbpin** [comment]
Ok I did it. Let me know if it's not working.. :/

**Comment by schiessle** [comment]
@jbpin the first commit is not signed. Maybe you can also squash the 5 commits into one?

**Comment by jbpin** [comment]
Ok looks ugly let's close this one and get another fresh ! I try to reset --soft for the commit and signed it but now we have conflict. 
What do you think ?

**Comment by schiessle** [comment]
yes, i think that's the best

**Pull request closed without merging**
