### PR TITLE
Replace tab based design with a scrollable design

### PR DESCRIPTION
**Pull request by MorrisJobke**
Before:

bildschirmfoto 2016-06-30 um 16 41 55
bildschirmfoto 2016-06-30 um 16 41 58
bildschirmfoto 2016-06-30 um 16 42 01

After:

bildschirmfoto 2016-06-30 um 16 39 07

Optional settings could be expanded by clicking on the text:

bildschirmfoto 2016-06-30 um 16 39 49
bildschirmfoto 2016-06-30 um 16 39 52
bildschirmfoto 2016-06-30 um 16 40 01

cc @nextcloud/designers @LukasReschke

### CODE REVIEW

**Comment by LukasReschke** [comment]
Woah! Awesome sauce! Thanks a lot, @MorrisJobke! 🚀 ❤️ 👯 

👍

**Comment by mar1u5** [comment]
👍

**Comment by jancborchardt** [comment]
Wow man, that was really ugly before and you fixed it! :) Thanks a lot :rocket:

**Comment by LukasReschke** [comment]
Hey! Jan! That's not ugly! Just *uhm* special ;-)

**Pull request merged**
