### PR TITLE
fix height of select box to select the IDP

### PR DESCRIPTION
**Pull request by schiessle**
the combobox is to small on Nextcloud 15 to fit in the text. This fixes it.

### CODE REVIEW

**Comment by skjnldsv** [comment]
How can I test? :)

**Comment by skjnldsv** [comment]
Hum, I'm not seeing anything :p
Should it add a select on the login page? After login?
I don't really know :p

Or if you want you can also just put a screenshot here :see_no_evil: :grin:

**Comment by schiessle** [comment]
@juliushaertl you need to logout, it is about the login screen... :wink: 

Before:

image


After:

image

**Comment by skjnldsv** [comment]
> @juliushaertl you need to logout, it is about the login screen...

Well, I did (skjnldsv), but had nothing on the login page.
I probably miss a setting somewhere.
Looks good anyway :+1:

**Pull request merged**
