### PR TITLE
Group mapping

### PR DESCRIPTION
**Pull request by bne86**

### CODE REVIEW

**Comment by bne86** [comment]
Some updates on this topic?

**Comment by anicoa** [comment]
any chance to get this merged? would be a great enhancement...

**Comment by anicoa** [comment]
@LukasReschke sorry to bother you. just want to know if i can support somehow to get this pr merged? thank you very much!

**Comment by pac0san** [comment]
Ok. Thank you for the information.

Paco.-

**Comment by schiessle** [comment]
closed in favour of https://github.com/nextcloud/user_saml/pull/185

**Pull request closed without merging**
