### PR TITLE
Bump xmlseclibs to 3.0.3

### PR DESCRIPTION
**Pull request by rullzer**
For php 7.3 compatibility

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
@schiessle ping

**Comment by pfy** [comment]
The default docker nextcloud production image did switch to php7.3 two days ago. user_saml ist now broken in nextcloud:production. Please merge.
https://github.com/nextcloud/docker/issues/714

**Comment by pfy** [comment]
I testet the current nextcloud:production container with php 7.3. This branch works, the current master and the current version in the nextcloud app store not.

**Comment by GuillauG** [comment]
Thanks for the fix ! (same issue here)
It really helped me...

**Pull request merged**
