### PR TITLE
Update test deps and integration test fixes

### PR DESCRIPTION
**Pull request by blizzz**
locally i get green lights finally \o/

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Are you sure you want to ship the vendor dir of the tests folder?

**Comment by blizzz** [comment]
Yes, it was like this before and I would like to not spent more time than necessary on this.

**Comment by blizzz** [comment]
> 2019-04-10 21:37:57,923 - INFO [net.shibboleth.idp.authn.impl.ValidateUsernamePasswordAgainstLDAP:139] - Profile Action ValidateUsernamePasswordAgainstLDAP: Login by 'student1' succeeded 
>  2019-04-10 21:37:57,925 - ERROR [net.shibboleth.idp.profile.impl.ResolveAttributes:240] - Profile Action ResolveAttributes: Error resolving attributes: Invalid Attribute resolver configuration 

Seems that's the current blocker.

**Comment by blizzz** [comment]
We are green eventually!!!

**Pull request merged**
