### PR TITLE
feat(server): master works now with upcoming NC 28

### PR DESCRIPTION
**Pull request by blizzz**
bump is needed for https://github.com/nextcloud/user_saml/pull/764

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]
Failures seem expected due to missing #764

**Comment by blizzz** [comment]
So much to clean up now. Rabbit holes everywhere.

**Comment by blizzz** [comment]
> Failures seem expected due to missing #764

Took a bit different approaches and removed usage of deprecated `IAppContainer` in `Application` and went for public `\OCP\Server` for other on-the-fly injections. In one class i could just use the `IEventDispatcher` that was actually already passed in the constructor.

**Comment by blizzz** [comment]
That's just leaves the stub to be taken over from or in #764 actually

**Pull request merged**
