### PR TITLE
Fix validating SAML XML schemas

### PR DESCRIPTION
**Pull request by nickvergessen**

### CODE REVIEW

**Comment by juliushaertl** [comment]
- [ ] We'll need a follow up issue to see how we proceed with the custom patched 3rdparty

**Review by juliushaertl — APPROVED** [review]
Tested and works

**Comment by nickvergessen** [comment]
We can also move the patch outside, and wrap each 3rdparty interaction instead

**Review by blizzz — CHANGES_REQUESTED** [review]
let's not patch third party, packaging might override it

**Comment by blizzz** [comment]
@nickvergessen @juliushaertl did the adjustments, and it is working on my test setup. If I get green lights from you, I'd clean up the commits before merging.

**Review by juliushaertl — APPROVED** [review]
Works here as well and code looks good 👍

**Comment by patschi** [comment]
FWIW, I was experiencing same issues and driving me insane. Narrowed it down to XML validation today morning too. Applying this patch fixes it in my affected setup with ADFS too.

**Pull request merged**
