### PR TITLE
Add test for ensuring keeping of displayname

### PR DESCRIPTION
**Pull request by LukasReschke**
There seems to be a bug here, let's try to track it down with integration tests.

Fixes https://github.com/nextcloud/user_saml/issues/119, fixes https://github.com/nextcloud/user_saml/issues/125

Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

### CODE REVIEW

**Comment by LukasReschke** [comment]
```
# FeatureContext::thUserValueShouldBe()
    And The user value "display-name" should be "Default displayname of student1"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # FeatureContext::thUserValueShouldBe()
      Expected Default displayname of student1 as value but got student1 (UnexpectedValueException)
```

**Comment by LukasReschke** [comment]
Sent to owner of affected instance and awaiting feedback.

**Comment by MorrisJobke** [comment]
This array index reminds me of another PR or was this in user_saml? 🤔

**Comment by MorrisJobke** [comment]
> This array index reminds me of another PR or was this in user_saml? 🤔

https://github.com/nextcloud/user_saml/pull/132/files?w=1

**Pull request merged**
