### PR TITLE
Handle mobile login flow with direct=1

### PR DESCRIPTION
**Pull request by CarlSchwan**
Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
tests false negative (they succeeded vice versa in previous run).

**Comment by blizzz** [comment]
this app does not follow the server-oriented stable branches approach.

**Pull request merged**
