### PR TITLE
make testEncodedObjectGUID more robust against false positives

### LINKED ISSUE #504: UID mapping not working properly
### Steps to reproduce
1. Enable SAML SSO and attribute UID mapping, use "email" as UID
2. Login

### Expected behaviour

I am logged in with the UID set to my user name.

### Actual behaviour

A new user with the UID "796B776A-2BAB-B79D-289E-CBA5B629E06A" is created instead. I'm not yet sure what it depends on, because I did not observe this behavior on another instance with a very similar configuration. Further, it seems to have surfaced suddenly. A debug log correctly lists the attributes passed to user_saml, I just can't share it due to privacy reasons.

### Server configuration

NC 20.0.5. with user_saml 3.3.3, auto-provisioning of SAML users allowed.

PHP: 7.3.24

### Possible cause

Commit https://github.com/nextcloud/user_saml/commit/9f53230eb6e1c97b006be30fb83fc230b09534eb changed the way `testEncodedObjectGUID` works, the parameter `strict` to `base64_decode` is set to false. I'm not sure how to interpret the description in the PHP manual, but IMHO `base64_decode` will almost never return false if `strict` is also false, because it simply skips characters it can't decode. 
If I change strict from false to true, I can log in: https://github.com/nextcloud/user_saml/blob/b406b6bdfa7515690695be400348161f6fbfd8b5/lib/UserBackend.php#L705

### PR DESCRIPTION
**Pull request by blizzz**
There are some collisions possible. The received string is now tested against allowed characters as put down in https://tools.ietf.org/html/rfc4648#section-4

* [ ] https://github.com/nextcloud/docker-ci/pull/261
* fixes #504

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
Backport as well I guess

**Comment by blizzz** [comment]
> Backport as well I guess

o'course

**Comment by blizzz** [comment]
bumped the integration test in the search of green lights. The latter commit ought not to be backported thus.

**Pull request merged**
