### PR TITLE
Spelling: XML, exists

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Please also update the strings in the unit tests.

**Comment by comradekingu** [comment]
@MorrisJobke Like so?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Like so?

Those two are still failing:

```
1) OCA\User_SAML\Tests\Settings\AdminTest::testGetFormWithoutType
-                'text' => 'Only allow authentication if an account is exists on some other backend. (e.g. LDAP)'
+                'text' => 'Only allow authentication if an account exists on some other backend. (e.g. LDAP)'
2) OCA\User_SAML\Tests\Settings\AdminTest::testGetFormWithSaml
-                'text' => 'Only allow authentication if an account is exists on some other backend. (e.g. LDAP)'
+                'text' => 'Only allow authentication if an account exists on some other backend. (e.g. LDAP)'
```

**Comment by MorrisJobke** [comment]
Squashed the commits and dropped the change in the vendor file PHP comment.

**Pull request merged**
