### PR TITLE
Implement new SLO URL API

### PR DESCRIPTION
**Pull request by LukasReschke**
For https://github.com/nextcloud/server/pull/6177

Fixes https://github.com/nextcloud/user_saml/issues/112

### CODE REVIEW

**Comment by LEDfan** [comment]
Shouldn't this be backported to stable12, since https://github.com/nextcloud/server/pull/6311 also has been backported?

**Comment by LukasReschke** [comment]
Master is released for stable12 and master on the appstore :) .

**Comment by blizzz** [comment]
@LukasReschke this patch was not applied to this apps stable12 branch, thus is not included in the release on  the appstore.

**Comment by LukasReschke** [comment]
@blizzz No. Master is used for building the app for the appstore release as well. But no new release has been put on the appstore yet.

The stable12 branch here is dead.

**Comment by blizzz** [comment]
@LukasReschke Alright, thanks for making it clear!

**Pull request merged**
