### PR TITLE
Update version on master

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by rullzer** [comment]
CI fails

**Comment by nickvergessen** [comment]
>   [Exception]                                                                                                        
App "SSO & SAML authentication" cannot be installed because it is not compatible with this version of the server. 

But I don't get it, why it only fails on integration tests and all others can install the app just fine.

**Comment by nickvergessen** [comment]
cc @LukasReschke if you have time

**Comment by LukasReschke** [comment]
Master will work on 12 and 13 via the appstore and there are also integration tests in place which test against 12 and 13. Thus closing :)

**Pull request closed without merging**
