### PR TITLE
Splitting CI images into seperate ones

### LINKED ISSUE #688: Update CI continuous-integration-user_saml_shibboleth-php8.0 image for master
continuous-integration-user_saml_shibboleth-php8.0:latest is based on unicon/shibboleth-idp:3.4.3, which itself is based on CentOS 7. It ships sqlite 3.7 only, which errors on "SELECT * FROM PRAGMA_TABLE_INFO ("tablename");". System requirements specify RedHat 8 (=> CentOS 8) also.

unicon/shibboleth-idp is not maintained any longer either.

### PR DESCRIPTION
**Pull request by blizzz**
Resolves #688 and should make it easier to maintain

Far from ready, contains temporary code (e.g. concurring drone.yml and MSGH Action)

TODOs in the commit message while in draft

### CODE REVIEW

**Comment by juliushaertl** [comment]
master also fails with the PCNTL issue https://github.com/nextcloud/user_saml/actions/runs/5780120199/job/15663353789

**Comment by blizzz** [comment]
> master also fails with the PCNTL issue https://github.com/nextcloud/user_saml/actions/runs/5780120199/job/15663353789

bumping setup-php seemed to fix it

**Comment by SystemKeeper** [comment]
Posting here, but some infos are also related to https://github.com/nextcloud/docker-ci/pull/535



* Host is wrong in `attribute-filter.xml`, should be `<PolicyRequirementRule xsi:type="Requester" value="http://localhost:8080/index.php/apps/user_saml/saml/metadata" />` (port is missing)
* Comment out all imports in `/opt/shibboleth-idp/conf/attributes/default-rules.xml`, otherwise we will see duplicated attributes (which is a result of using v3 files in v4, see https://shibboleth.atlassian.net/wiki/spaces/IDP4/pages/1265631499/ReleaseNotes#Attribute-Related-Changes for details). Alternatively look how the new `AttributeRegistry` works...
* In `nextcloud.xml` we are also missing the port in `<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8080/index.php/apps/user_saml/saml/acs" index="1"/> `
* `/opt/shibboleth-idp/conf/oidc-credentials.xml` needs to exist and should look like:
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:context="http://www.springframework.org/schema/context" xmlns:util="http://www.springframework.org/schema/util" xmlns:p="http://www.springframework.org/schema/p" xmlns:c="http://www.springframework.org/schema/c" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd                            http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd                            http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util.xsd" default-init-method="initialize" default-destroy-method="destroy">
  <!-- This file contains default oidc signing credentials. This file should be imported to credentials.xml -->
  <!-- The list of ALL of your OP's ID Token / UserInfo response signing credentials for the default security configuration. 
        If you define additional signing credentials, for example for new supported signing algorithms, make sure to include them 
        within this list. -->
  <bean class="net.shibboleth.idp.profile.spring.factory.BasicX509CredentialFactoryBean" id="shibboleth.oidc.PEMSigningCredential" p:certificateResource="%{idp.signing.cert}" p:entityId-ref="issuer" p:keyNames="Signing" p:privateKeyResource="%{idp.signing.key}"/>
  <bean class="net.shibboleth.idp.profile.spring.factory.BasicX509CredentialFactoryBean" id="shibboleth.oidc.PEMEncryptionCredential" p:certificateResource="%{idp.encryption.cert}" p:entityId-ref="issuer" p:keyNames="Encryption" p:privateKeyResource="%{idp.encryption.key}"/>
  <util:list id="shibboleth.oidc.SigningCredentials">
    <ref bean="shibboleth.oidc.PEMSigningCredential"/>
  </util:list>
  <!-- The list of ALL of your OP's Request Object decryption credentials for the default security configuration. If you 
        define additional decryption credentials, for example to support new algorithm, make sure to include them within 
        this list. -->
  <util:list id="shibboleth.oidc.EncryptionCredentials">
    <ref bean="shibboleth.oidc.PEMEncryptionCredential"/>
  </util:list>
  <!-- If you need to publish key set different from shibboleth.oidc.EncryptionCredentials, define a list named as shibboleth.oidc.EncryptionCredentialsToPublish -->
  <alias name="shibboleth.oidc.EncryptionCredentials" alias="shibboleth.oidc.EncryptionCredentialsToPublish"/>
  <!--
    Example of case having two active encryption credentials but then stop publishing the second before removing it from active configuration.
    <util:list id="shibboleth.oidc.EncryptionCredentialsToPublish">
        <ref bean="shibboleth.oidc.OnlyNewDefaultRSAEncryptionCredential" />
    </util:list>
    -->
  <!-- If you need to publish key set different from shibboleth.oidc.SigningCredentials, define a list named as shibboleth.oidc.SigningCredentialsToPublish -->
  <alias name="shibboleth.oidc.SigningCredentials" alias="shibboleth.oidc.SigningCredentialsToPublish"/>
  <!--
    Example of case publishing signing credential before taking it to active configuration: 
    
    <util:list id="shibboleth.oidc.SigningCredentialsToPublish">
        <ref bean="shibboleth.oidc.DefaultRSSigningCredential" />
        <ref bean="shibboleth.oidc.DefaultESSigningCredential" />
        <ref bean="shibboleth.oidc.UpcomingDefaultRSSigningCredential" />
    </util:list>
    -->
</beans>
```

(from https://github.com/CSCfi/shibboleth-idp-dockerized/blob/master/opt/shibboleth-idp/conf/credentials-oidc.xml, haven't compared, but should be the same I guess, **note the order**, the file in the container is called `credentials-oidc.xml`, but we need `oidc-credentials.xml`! See import in `credentials.xml`).

After that:

```
8 scenarios (8 passed)
119 steps (119 passed)
0m27.67s (10.09Mb)
```

😎

**Comment by blizzz** [comment]
@SystemKeeper muchos gracias! Some changes i had already locally like that, but you also saved me some more digging :heart:

**Comment by blizzz** [comment]
Screenshot_20231010_121007

happy

**Review by juliushaertl — APPROVED** [review]
Changes look good :+1: 

Long way but nice work :partying_face:

**Pull request merged**
