### PR TITLE
Catch exception during parameter fetching

### LINKED ISSUE #283: BLOCKING : user_saml app deactivates itself at random times
### Steps to reproduce
1. Install and activate user_saml with environment variable authentication
2. 
3. 

### Expected behaviour
The app should remain activated until manually deactivated

### Actual behaviour
The app deactivates itself at random times
It is necessary to manually reactivate the app

### Server configuration

**Operating system**:
Debian stretch 9.6
**Web server:**
Apache 2.4
**Database:**
Mariadb 10.1
**PHP version:**
7.0.30
**Nextcloud version:** (see Nextcloud admin page)
14.0.3
**Where did you install Nextcloud from:**

**List of activated apps:**
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - bruteforcesettings: 1.2.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - external: 3.1.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.5.1
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - piwik: 0.5.0
  - previewgenerator: 2.0.0
  - provisioning_api: 1.4.0
  - richdocuments: 3.0.5
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_external: 0.4
  - user_ldap: 1.4.0
  - user_saml: 2.1.0
  - workflowengine: 1.4.0

**Nextcloud configuration:**

```php
$CONFIG = array (
  'instanceid' => 'XX',
  'passwordsalt' => 'XX',
  'datadirectory' => 'XX',
  'asset-pipeline.enabled' => false,
  'dbtype' => 'mysql',
  'version' => '14.0.3.0',
  'dbname' => 'XX',
  'dbhost' => 'XX',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XX',
  'dbpassword' => 'XX',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => false,
  'log_type' => 'syslog',
  'loglevel' => 0,
  'mail_domain' => 'XX',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'XX',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => 30,
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\Illustrator',
    4 => 'OC\\Preview\\Postscript',
    5 => 'OC\\Preview\\Photoshop',
    6 => 'OC\\Preview\\TIFF',
  ),
  'theme' => 'XX',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'trusted_domains' => 
  array (
    0 => 'XXXXXXXXXXX',
    1 => 'XXXXXXXXXXXXXXX',
  ),
  'share_folder' => '/Shared',
  'mail_from_address' => 'noreply',
  'secret' => 'XX',
  'trashbin_retention_obligation' => 'auto',
  'appstore.experimental.enabled' => false,
  'updater.release.channel' => 'production',
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'overwrite.cli.url' => 'https://XX',
  'knowledgebaseenabled' => false,
  'integrity.check.disabled' => true,
);
```
### Client configuration
**Browser:**

**Operating system:**

### Logs
No logs for user_saml
#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
Not relevant
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #283 

This avoids diabling the user_saml app on random PUT requests to the Nextcloud instance without a proper Content-Type.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@juliushaertl Mind to do the backport manually because the bot seem to crash?

**Comment by juliushaertl** [comment]
@MorrisJobke There seem to be no stable branches for user_saml. I guess @schiessle just released from master as it is currently marked to be compatible for 14-17
https://github.com/nextcloud/user_saml/blob/master/appinfo/info.xml#L33

**Pull request merged**
