### PR TITLE
Allow customer directlogin text

### PR DESCRIPTION
**Pull request by rullzer**
Some people seem to want to have a custom direct login text. This allows
them to set it. For now only via occ. But maybe some day we also add a
GUI component to it.

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Review by blizzz — COMMENTED** [review]
does not help with multiple saml configurations

**Comment by blizzz** [comment]
> does not help with multiple saml configurations

Oh wait, I just realized this is renaming the direct login, and not the SAML providers themselves

**Comment by rullzer** [comment]
> > does not help with multiple saml configurations
> 
> Oh wait, I just realized this is renaming the direct login, and not the SAML providers themselves

exactly :)

**Review by blizzz — APPROVED** [review]

**Review by juliushaertl — APPROVED** [review]
Yay :tada:

**Pull request merged**
