### PR TITLE
change displayName with IEventDispatcher

### PR DESCRIPTION
**Pull request by Superjamp**

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]
Tested and fixes the issue I was hunting 👍

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
CI phpunit fails, seems like an issue with the tests themselves though.

**Comment by Superjamp** [comment]
@juliushaertl 👍 
I came across this some time ago and now I have not found a good explanation of the way you did it for a pull request.  
But it is the same Issue/steps to reproduce I had last year.

**Comment by juliushaertl** [comment]
I've pushed your commit with an additional one for the tests to https://github.com/nextcloud/user_saml/pull/582

**Comment by blizzz** [comment]
superseded by #582

**Pull request closed without merging**
