### PR TITLE
Explicitly set authncontext

### PR DESCRIPTION
**Pull request by LukasReschke**
Should help with ADFS

Ref https://github.com/nextcloud/user_saml/issues/23#issuecomment-247874576

### CODE REVIEW

**Comment by MichaelHeimann** [comment]
@LukasReschke Thanks, that works great and also fixes a problem with external access which I discovered.

**Comment by LukasReschke** [comment]
I'll merge that then once I've added some automatic integration tests for Shibboleth to ensure it won't add any regressions.

**Comment by rzmf** [comment]
Why not setting authncontext = false?  if the idp allows login via some obscure mechanism it is up to the idp to allow login or not.

        'requestedAuthnContext' => false,

maybe also setting        'requestedAuthnContextComparison' => 'minimum'  would  be necessary

**Comment by Ollienator** [comment]
I agree with rzmf.  'requestedAuthnContext' should be set to false instead of explicitely requesting a set of authentication contexts.  If any authentication contexts are requested, it will override the authentication method settings configured on the ADFS server (e.g. X509, Windows, Forms).

See this comment from the onelogin repo:
```
        // Authentication context.
        // Set to false or don't present this parameter and no AuthContext will be sent in the AuthNRequest,
        // Set true and you will get an AuthContext 'exact' 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport'
        // Set an array with the possible auth context values: array ('urn:oasis:names:tc:SAML:2.0:ac:classes:Password', 'urn:oasis:names:tc:SAML:2.0:ac:classes:X509'),
        'requestedAuthnContext' => true,
```

**Comment by LukasReschke** [comment]
Fair enough. Will test with Shibboleth and OneLogin later as I'm anyways working on another feature that needs regression testing and if that works we can go the `requestedAuthnContext => false` route.

I won't have tested this against ADFS myself though. So I trust you, that you tested this 😉

**Comment by LukasReschke** [comment]
Will be in 11.0

**Pull request closed without merging**
