### PR TITLE
remove Nc 15 compatibility

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by blizzz** [comment]
Perhaps ditching 15 should wait for 2020? I believe this app is also released from master.

**Comment by nickvergessen** [comment]
Well I'm fine in all ways, my job here is done, may the maintainer of the app take over and go through the multi version support pain or pick another path.

**Comment by blizzz** [comment]
Then let's keep it open until 15 is EOL.

**Comment by blizzz** [comment]
already done in master

**Pull request closed without merging**
