### PR TITLE
Update saml library

### PR DESCRIPTION
**Pull request by LukasReschke**
Required for https://github.com/nextcloud/user_saml/pull/131 and https://github.com/nextcloud/user_saml/pull/129

### CODE REVIEW

**Comment by LukasReschke** [comment]
This breaks Shibboleth as per https://drone.nextcloud.com/nextcloud/user_saml/95/11 – let me look into this 🙈

**Comment by rullzer** [comment]
I just rebased on master. But there is something :fish:-y, As one CI run passed and the other failed.

**Comment by MorrisJobke** [comment]
Moved to 14.

**Comment by schiessle** [comment]
superseded by https://github.com/nextcloud/user_saml/pull/236

**Pull request closed without merging**
