### PR TITLE
Implemented PostLoginEvent in SAMLController

### PR DESCRIPTION
**Pull request by x7airworker**
This will also fix https://github.com/nextcloud/user_saml/issues/426.

### CODE REVIEW

**Comment by blizzz** [comment]
Tests need adjustments. 

Also I just got aware about https://github.com/nextcloud/user_saml/pull/851 with different event classes :confused:

**Comment by x7airworker** [comment]
Because I am using a custom user backend, I have no need for the events mentioned in https://github.com/nextcloud/user_saml/pull/851 although I agree that they should be implemented. I'll be happy to adjust the test cases if you can point me in the right direction. I am not familiar with writing tests for Nextcloud Apps and especially testing event dispatching, but I'll try my best.

**Comment by x7airworker** [comment]
@blizzz Could you take a look at my added test assertions?

**Comment by blizzz** [comment]
@x7airworker sure, I try to do it this week. Btw, pushing commits do not trigger Github notifications, a comment like yours now is helping catching attention :)

**Comment by blizzz** [comment]
> Tests need adjustments.
> 
> Also I just got aware about #851 with different event classes 😕

@x7airworker sorry for bringing this up late. I was checking with the server team, and indeed we have here a duplicated event for whatever reason. The goal is now set to sunset `PostLoginEvent` in favor of `UserLoggedInEvent`, which is also  consistent with the modern naming of events. Again apologies for the forth-and-back. 

Thus is is better to continue with #851 (i have to have a closer look at it still), but the tests would be relevant there just as well.

**Pull request closed without merging**
