### PR TITLE
MFA verification flag

### PR DESCRIPTION
**Pull request by navid-dada**
Adding MFA verification mapping configuration in the admin panel.
Adding the MFA verified flag Into the formatted user data in UserBackend.

### CODE REVIEW

**Review by michielbdejong — APPROVED** [review]

**Comment by come-nc** [comment]
Something went wrong with the PR, you have commits in there which are not yours. Could you try rebasing on master and check that your branch only contains your changes?

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
tests needs adjustments

**Comment by michielbdejong** [comment]
@blizzz tests are green now, sorry for the delay

**Comment by michielbdejong** [comment]
@mrvahedi68 some tests are still failing

**Comment by mrvahedi68** [comment]
@blizzz Now all tests passed except one integration test that has the same error on other pull requests on the master branch. Can review PR again?

**Comment by michielbdejong** [comment]
Bump

**Comment by blizzz** [comment]
I was OOO last weeks. Thank for your fixing the tests. The failing master integration should be unrelated, I like to doublecheck this anyway. Please stay tuned.

Just one question: Would the IdP actually send a successful authentication response despite failing/missing MFA?

**Comment by michielbdejong** [comment]
> Would the IdP actually send a successful authentication response despite failing/missing MFA?

Yes, authentication can be
1. failing
2. successful but no MFA
3. successful with MFA

**Comment by blizzz** [comment]
The failure is due to an incompatible sqlite3 version. The very base image of the container is centos7, where only sqlite 3.7 is available. We have to solve this, but it shall not block this PR.

**Comment by michielbdejong** [comment]
Thanks!

**Pull request merged**
