### PR TITLE
Bump to v5.2 and require at least NC 25

### PR DESCRIPTION
**Pull request by blizzz**
Needed for https://github.com/nextcloud/user_saml/pull/698 as bumping php-jwt would not be backwards compatible with older NC/GSS versions.

Additional stable26 testing added in #704

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by come-nc** [comment]
Codesniffer and drone are not happy.

**Comment by blizzz** [comment]
> Codesniffer and drone are not happy.

Drone is actually happy, but 26 and master fail because of incompatibilites with the OS of the test image. There'S #712  on going to fix this, but we're not there yet. 25 is the canaray for so long :(

**Comment by blizzz** [comment]
cannot reproduce the cs issue locally :-/

**Comment by blizzz** [comment]
> cannot reproduce the cs issue locally :-/

eh, can, with PHP7.4 instead of 8 :exploding_head:

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
