### PR TITLE
feat: migrate from deprecated PublicEmitter to IEventDispatcher

### PR DESCRIPTION
**Pull request by bdovaz**
Fixes https://github.com/nextcloud/user_saml/issues/853

### CODE REVIEW

**Comment by bdovaz** [comment]
@blizzz I have doubts with these lines:

https://github.com/nextcloud/user_saml/blob/edb21705e2963322d38e0323baccd9bad69e0976/tests/stub.phpstub#L29

Should I remove them? I don't really know what this file is for, I come from the .NET world.  😅

**Comment by blizzz** [comment]
> @blizzz I have doubts with these lines:
> 
> https://github.com/nextcloud/user_saml/blob/edb21705e2963322d38e0323baccd9bad69e0976/tests/stub.phpstub#L29
> 
> Should I remove them? I don't really know what this file is for, I come from the .NET world. 😅

So that's for testing, and the `PublicEmitter` is a private interface from the server, so it was stubbed here. By dropping that interface from `lib/GroupManager.php` we may do not need the stub anymore, and the entry can be removed just as well.

**Comment by bdovaz** [comment]
> > @blizzz I have doubts with these lines:
> > https://github.com/nextcloud/user_saml/blob/edb21705e2963322d38e0323baccd9bad69e0976/tests/stub.phpstub#L29
> > 
> > Should I remove them? I don't really know what this file is for, I come from the .NET world. 😅
> 
> So that's for testing, and the `PublicEmitter` is a private interface from the server, so it was stubbed here. By dropping that interface from `lib/GroupManager.php` we may do not need the stub anymore, and the entry can be removed just as well.

Removed! PR ready to review!

**Comment by blizzz** [comment]
There is failing CI. I see this also in an unrelated PR, so it do not think it is related to your changes. Nevertheless, I want to have this sorted out first so we have a green CI by default :)

**Comment by blizzz** [comment]
> There is failing CI. I see this also in an unrelated PR, so it do not think it is related to your changes. Nevertheless, I want to have this sorted out first so we have a green CI by default :)

It was a regression within server, but fixed now.

**Review by blizzz — APPROVED** [review]

**Comment by blizzz** [comment]
Now unit tests, they need adjustements. The IEventDispatcher has to be passed here https://github.com/nextcloud/user_saml/blob/master/tests/unit/GroupManagerTest.php#L57-L58 and maybe we want to check that `dispatchTyped()` is called with the correct event class.

**Comment by bdovaz** [comment]
@blizzz done! Please rerun, thanks!

Is there any way to run the tests locally so that I don't depend on you to approve the workflow execution? Because looking at this file it seems that it depends on the fact that they must be executed through the workflow:

https://github.com/nextcloud/user_saml/blob/1a180957787d140af00d861847cc159cd84c0439/tests/unit/bootstrap.php#L10

**Comment by blizzz** [comment]
If you have user_saml in an apps folder in a server checkout running locally will work. `composer i && composer run test:unit` should be sufficient then.

**Comment by bdovaz** [comment]
@blizzz now I hope that everything is corrected, locally at least everything works correctly.

My problem was that I did not understand well the PHPUnit API and expects method when we want to check multiple invocations with different parameters of a method.

In my case I have not used the "at" method that is used in "UserBackendTest.php" because it says that it is deprecated and will be removed in the next version of PHPUnit. I could correct the one in "UserBackendTest.php" but I don't want to do it in this PR to avoid touching files that I should not.

**Comment by bdovaz** [comment]
@blizzz I don't understand the errors that appear in the MySQL workflow, if the tests are exactly the same and in other database providers they have worked correctly (SQLite and PostgreSQL) how is it possible that in MySQL not and with this error?

```
1) OCA\User_SAML\Tests\GroupManagerTest::testUpdateUserGroups
Creation of dynamic property OCA\User_SAML\Tests\GroupManagerTest::$eventDispatcher is deprecated

/home/runner/actions-runner/_work/user_saml/user_saml/apps/user_saml/tests/unit/GroupManagerTest.php:50
```

image

**Comment by bdovaz** [comment]
@blizzz I have corrected it anyway, it is that the field at class level was missing. The strange thing as I say is that it fails in some workflows but not in others. Apart from the fact that it is a warning but in reality it considers it an error.

You can run the build again.

**Comment by blizzz** [comment]
> @blizzz I have corrected it anyway, it is that the field at class level was missing. The strange thing as I say is that it fails in some workflows but not in others. Apart from the fact that it is a warning but in reality it considers it an error.
> 
> You can run the build again.

Thanks! Dynamic properties were deprecated in PHP 8.2, so earlier ones would pass.

**Comment by bdovaz** [comment]
@blizzz have passed all the checks!

Merge whenever you want, I'm all set!

Thanks.

**Comment by blizzz** [comment]
Great! Thank you @bdovaz !

**Pull request merged**
