### PR TITLE
Alternative logins

### PR DESCRIPTION
**Pull request by bne86**
Only as starting point:
Provide way to allow several logins at the same time, for example the integrated Nextcloud user database and SAML. Or LDAP and SAML...
For this, utilize the "Alternative Logins" part of the login screen

### CODE REVIEW

**Comment by bne86** [comment]
Some updates here? Currently this is a show stopper for us.

**Comment by bne86** [comment]
Some updates here? Currently this is a show stopper for us.

**Comment by cellisten** [comment]
Any progress? In #126 @LukasReschke mentions that he might have time to do it in September. I have a use case where we need to allow external users to login with local accounts rather than SSO.

**Comment by schiessle** [comment]
solved with this pr https://github.com/nextcloud/user_saml/pull/196 and released in v1.5.0

**Pull request closed without merging**
